### ISSUE TITLE
What have I done wrong? | Что Я сделал не так?

### ISSUE THREAD

**Issue by ImGr0k** [commeta/modxWebpConverter#1]
1. Step one
![изображение](https://user-images.githubusercontent.com/46184354/91079453-bb26b300-e64c-11ea-9f6a-f13447f5ced9.png)
2. Step two
![изображение](https://user-images.githubusercontent.com/46184354/91079672-093bb680-e64d-11ea-839d-e1a76a1a562f.png)
![изображение](https://user-images.githubusercontent.com/46184354/91079761-283a4880-e64d-11ea-9cd2-711ac18bd565.png)
3. Step three
![изображение](https://user-images.githubusercontent.com/46184354/91079917-659ed600-e64d-11ea-83c3-0b447bac350b.png)

**Comment by commeta** [comment]
Your operating system is not defined, tell me what your OS (windows?, linux?, macos?) and version of php?
Ваша операционная система не опредилась, подскажите какая у вас ось (windows?, linux?, macos?) и версия php?

**Comment by ImGr0k** [comment]
Спустя время, до сих пор не работает.

Операционная система на хостинге **CentOS (Линукс)**

Я видел, что вы обновили дистрибутив, Я все заново скачал и проделал работы заново. Теперь вытекло две проблемы:

**Проблема 1:**
Когда Я делаю плагин статичным выдаёт ошибку в Modx (screen 1), если не статичным тогда нет проблемы. Путь до статичного файла верный (screen 2/screen 3).

**Проблема 2:**
Если файл не статичный то при нажатии Webp Конвектор - ничего не происходит. Если файл статичный выдаёт ошибку: "Bin file not work! return code: %11%".

Никаких плагинов для кэша не стоит.

Даже если брать установщики с сайта гугла, Я не совсем понимаю что с ними делать, пожалуйста, напишите пошагово что мне нужно делать (не для гиков).

P.S. Я русскоязычный, можем вести диалог по-русски, перевожу на английский, вдруг кому-то понадобиться.
***
After a while, it still does not work.

Operating system hosted by **CentOS (Linux)**

I saw that you updated the distribution, I downloaded everything again and did the work again. Now two problems have emerged:

**Problem 1:**
When I make a plugin static it gives an error in Modx (screen 1), if not static then there is no problem. The path to the static file is correct (screen 2 / screen 3).

**Problem 2:**
If the file is not static, then when you press Webp Convector, nothing happens. If the file is static, it gives the error: "Bin file not work! Return code:% 11%".

No cache plugins are needed.

Even if you take the installers from the Google website, I don't quite understand what to do with them, please write step by step what I need to do (not for geeks).

P.S. I am Russian-speaking, we can conduct a dialogue in Russian, I translate into English, suddenly someone needs it.

***
Screen 1
![screen 1](https://user-images.githubusercontent.com/46184354/93330415-6e875f80-f827-11ea-94cb-a944a8ce67c2.jpg)
***
Screen 2
![screen 2](https://user-images.githubusercontent.com/46184354/93330455-79da8b00-f827-11ea-9e2a-8be307f77ee0.jpg)
Screen 3
![screen 3](https://user-images.githubusercontent.com/46184354/93330471-7f37d580-f827-11ea-93bd-f0d288e6fb1d.jpg)
***
Screen 4
![screen 4](https://user-images.githubusercontent.com/46184354/93330481-82cb5c80-f827-11ea-9a59-a46e9309e9ae.jpg)

**Comment by commeta** [comment]
> Операционная система на хостинге CentOS (Линукс)

покажите вывод
`uname -a`
из консоли

> **Проблема 1:**
> Когда Я делаю плагин статичным выдаёт ошибку в Modx (screen 1), если не статичным тогда нет проблемы. Путь до статичного файла верный (screen 2/screen 3).

Видимо необходимо полностью удалить каталог /core/cache, т.к. видна попытка повторного определения функции check_image_file(), чего быть не должно, видимо застряла в кэше.

> **Проблема 2:**
> Если файл не статичный то при нажатии Webp Конвектор - ничего не происходит. Если файл статичный выдаёт ошибку: "Bin file not work! return code: %11%".

Бинарник утилиты возвращает ошибку, вам удобнее будет войти на сервер через SSH, и вручную запустить бинарники от линукс, (покажите сообщения об ошибках) тогда будет ясно почему ни один не запустился. 

> Даже если брать установщики с сайта гугла, Я не совсем понимаю что с ними делать, пожалуйста, напишите пошагово что мне нужно делать (не для гиков).

Тут все просто, заходим на https://storage.googleapis.com/downloads.webmproject.org/releases/webp/index.html
скачиваем последнюю версию для линукс, например libwebp-1.1.0-rc2-linux-x86-64.tar.gz  
Распаковываем, ~/libwebp-1.1.0-linux-x86-64/bin/cwebp это и есть нужный нам бинарник, кладем его в каталог на сервере.

Как подключать бинарник подробно написано:
https://github.com/commeta/modxWebpConverter/tree/master/Binaries
https://webdevops.ru/blog/webp-converter-plugin-modx.html

Все это лучше делать в консоли через SSH, последовательно попробовать все версии, может вам нужна более старая версия?
Держите в курсе.

**Comment by ImGr0k** [comment]
Дополняю информацией.

> покажите вывод

![uname a](https://user-images.githubusercontent.com/46184354/93447998-c2ec1700-f8db-11ea-924a-000983c412b2.jpg)
Текстом:
```
Linux server246.hosting.reg.ru 3.10.0-1127.18.2.el7.x86_64 #1 SMP Sun Jul 26 15:27:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
***
**По проблеме 1:**
Папку с кешом удалял в первую очередь, очищал кеш через админку, перезагружал права доступа, завершал все сеансы (все стандартные операции) — это не помогает.

Ошибка выпадает когда ставишь галочку "OnPluginSave", если файл статичный. Если её не ставить, ошибок нет, в независимости статичный файл или нет.

Из странного, что обнаружил:
У меня нажимается кнопка "WEBP Конвертор", только в режиме инкогнито. В Firefox и Chrome (хром чистый без плагинов), кнопка не реагирует. Какая то глубокая проблема с кешем?

***
**По проблеме 2:**
Что бы Вы понимали мои познания в терминале, мой максимум это перемещаться по директориям. Скажите какой командой запускается бинарник, и Я тут же запущу и дам информацию!

**Comment by commeta** [comment]
1. Если у вас есть root доступ к серверу, вы можете установить 100% рабочую версию утилиты из репозитория:
`yum install libwebp-tools`
И скопировать её в каталог сайта (указав ваш путь к сайту на сервере)
`cp /usr/bin/cwebp /path/to/site/on/server/site.com/connectors/converter/Binaries/cwebp`

После в фале converter.php - заменить массив на
`$suppliedBinaries= ['linux' => 'cwebp'];`

2. По проблеме 1: Мне пока не есно откуда у вас появляется ошибка, попробуйте в файле modx_plugin_webp_converter.php
заменить все строки check_image_file на check_image_file_for_webp_converter.

> Из странного, что обнаружил:

А если нажать F12 и посмотреть какие ошибки в консоли при клике?

3. По проблеме 2:
Бинарник запускается просто, надо набрать полный путь до файла, и нажать enter
`/path/to/site/on/server/site.com/connectors/converter/Binaries/cwebp-110-linux-x86-64`
`/path/to/site/on/server/site.com/connectors/converter/Binaries/cwebp-061-linux-x86-64`
`/path/to/site/on/server/site.com/connectors/converter/Binaries/cwebp-103-linux-x86-64-static`

Только замените /path/to/site/on/server/site.com/ на путь вашего сайта на сервере.
