### ISSUE TITLE
Кастомные теги изображения

### ISSUE THREAD

**Issue by angelok1979** [commeta/modxWebpConverter#15]
Плагин находит только первое вхождение "data-src" для подмены на webp. В случае когда сделано кастомное разделение на разные устройства, не находятся  data-mobile-src= , data-mobile-mobile-src= и data-mobile-src-mini=

было

`<img class="lazyload" data-src="/webp/images/content/img-main-slider10-ru.jpg" data-mobile-src="images/content/img-main-slider10-ru-mob.jpg" data-mobile-mobile-src="mobile-images/content/img-main-slider10-ru-mob.jpg" data-mobile-src-mini="images/content/img-main-slider10-ru-mob-mi.jpg" alt="">`

стало

`<img class="lazyload" data-src="/webp/images/content/img-main-slider10-ru.jpg.webp" data-mobile-src="images/content/img-main-slider10-ru-mob.jpg" data-mobile-mobile-src="mobile-images/content/img-main-slider10-ru-mob.jpg" data-mobile-src-mini="images/content/img-main-slider10-ru-mob-mi.jpg" alt="">`

надо

`<img class="lazyload" data-src="/webp/images/content/img-main-slider10-ru.jpg.webp" data-mobile-src="images/content/img-main-slider10-ru-mob.jpg.webp" data-mobile-mobile-src="mobile-images/content/img-main-slider10-ru-mob.jpg.webp" data-mobile-src-mini="images/content/img-main-slider10-ru-mob-mi.jpg.webp" alt="">`

если поиск делается до первого вхождения то варианты:
- сделать полный поиск
- сделать конфиг, где можно добавлять кастомные параметры, так как другие программисты могут сувать url в невалидные параметры

**Comment by commeta** [comment]
В файле modx_plugin_webp_converter.php 159 строка:
`preg_match('/(src|data-src|data-background)=("[^"]*")/i', $img_tag, $img[$img_tag]);`

добавьте свои аттрибуты, пример:
`preg_match('/(src|data-src|data-background|data-mobile-src-mini|data-mobile-mobile-src|data-mobile-src)=("[^"]*")/i', $img_tag, $img[$img_tag]);`

**Comment by angelok1979** [comment]
Спасибо за оперативный ответ. Это круто.
Внес правку по вашему описани:
//preg_match('/(src|data-src|data-background)=("[^"]*")/i', $img_tag, $img[$img_tag]);					
preg_match('/(src|data-src|data-background|data-mobile-mobile-src|data-mobile-src-mini|data-mobile-src)=("[^"]*")/i', $img_tag, $img[$img_tag]);

как запустить заново проверку чтобы обновленные теги нашлись? 
нажатие кнопки плагина сообщило что поискало, завершено, журнал пуст и изменения нет.

**Comment by commeta** [comment]
Кэш MODX сбросьте

**Comment by angelok1979** [comment]
Консоль запущена...
PHP warning: file_put_contents(/home/admin/web/какой-то домен/public_html/connectors/converter/converter.flg): Failed to open stream: Permission denied
Обработка дат автоматической публикации
-> 0 документов было опубликовано.
-> 0 документов было снято с публикации.
Обновление кэша системных настроек: Обновлено успешно!
Обновление кэша контекста
-> mgr: Обновлено успешно!
-> web: Обновлено успешно!
Очистка кэша запросов к базе данных: Обновлено успешно!
Очистка кэша источников файлов: Обновлено успешно!
Очистка кэша записей словаря: Обновлено успешно!
Очистка кэша сниппетов/плагинов: Обновлено успешно!
Очистка основного кэша: Обновлено успешно!
Очистка кэша ресурсов: Обновлено успешно!
Очистка кэша меню: Обновлено успешно!
Очистка кэша карты действий: Обновлено успешно!


проверка по фтп показала что в папке /connectors/converter/  файла   converter.flg нет
результат все тот же.

**Comment by angelok1979** [comment]
судя по тиишине, я так понимаю что решения в рамках выстроенной вами логике нет? если вы скажете что мой случай частный и сошлетесь на пресеты что у вас учтены, то не соглашусь.


как позывают измерения loading="lazy" уступает кастомной загрузке в зависимости от устройства. а в этой ситуации логично ставить в картинки в разные data-
  
как пример pikabu.ru
<img data-src="https://cs15.pikabu.ru/post_img/2024/09/06/7/1725618049129492375.jpg" src="" data-large-image="https://cs15.pikabu.ru/post_img/2024/09/06/7/1725618049129492375.jpg" class="story-image__image" data-viewable="true" alt="Время не щадит никого Юмор, Сериал Клиника, От винта">

**Comment by commeta** [comment]
Мне честно говоря не ясна архитектура вашего приложения, да и времени нет разбираться.
Могу посоветовать перечитать документацию, проверить настройки событий, логи ошибок, тестовую старницу, наличие файлов в подкаталоге /webp и т.д. 

Плагин осуществляет подмену после рендера MODX, перед отдачей контента в браузер, если есть другие плагины обработки контента - они могут конфликтовать.

**Comment by angelok1979** [comment]
дело не в моей архитектуре. у вас не хватает одного цикла для перебора нескольких параметров у одно тега
тоесть вы отрабатываете максимум один data- параметр на тег
<img data-src="url.jpg">

но ваша констсрукция не отработает оба тега для
<img data-scr1="url1.jpg" data-scr2="url2.jpg">
а только один. и я вам на вскидку дал пример с большого популряного  сайта, где такое же используется. тоесть это не моя экзотика, а у вас неучтен популярный случай. если "нет времени", то это ваше дело и будущее вашего детища. я и сам себе доработаю.

**Comment by commeta** [comment]
Для этого я и выложил, если ВАМ надо ВЫ для себя сделаете так как вам надо. Можете написать свою версию, можете использовать в ней мои идеи, а можете и вовсе отказаться от использования, это не коммерческий проект.

**Comment by angelok1979** [comment]
понял. тогда закрываю issue за бесполезностью.

**Comment by commeta** [comment]
Оптимизировал код, поменял цикл на DOMDocument, но оно и на прошлой версии 2 атрибута в одном теге нормально парсило

**Comment by angelok1979** [comment]
спасибо за желание улучшить.
вижу что сделали рефакторинг и добавили еще случаи.

вчера дописывал ваш старый код, но решил взять ваш новый

вижу что писали уже ночью, потому строки 176-186 лучше заменить на


$seektags = array('src','data-src','data-background','srcset','style');
foreach($seektags as $itm)
{
	check_image_file_for_webp_converter( $element->getAttribute($itm), $webp_on_page);
}

данное изменение чуть изящнее и удобнее для добавления другими коллегами своих кастомных тегов.

в строки 160-164 не стал вдумываться. но чую там тоже что-то ночное...

ваш новый код работает. вы молодец что нашли время поддержать свое детище. теперь меняются и несколько параметров, и несколько <link href=.... 

======================================================================================================


ну что бы не думали что я сидел и ждал от вас решение, скину  свои вчерашние изменения, которые тоже работают:

1. перед строкой 180 добавил для <link href="ссылканакартинку" >  используется для пролода картинок

`    	preg_match_all('/<link[^>]+>/i', $output, $result);
    	if(count($result)){ // Search images in a href tag
    		foreach($result[0] as $img_tag)	{
    			$img_tag= str_replace("'", '"', $img_tag); // src
    			preg_match('/(href)=("[^"]*")/i', $img_tag, $img[$img_tag]);						
    			$img_real= str_replace('"', '', $img[$img_tag][2]);
    			check_image_file_for_webp_converter($img_real, $webp_on_page);
    		}
    	}
`

2. выше заменил три строки
`preg_match('/(src|data-src|data-background)=("[^"]*")/i', $img_tag, $img[$img_tag]);
$img_real= str_replace('"', '', $img[$img_tag][2]);
check_image_file_for_webp_converter($img_real, $webp_on_page);
`
на
`preg_match_all('/(src|data-src|data-background|data-mobile-mobile-src|data-mobile-src-mini|data-mobile-src)=("[^"]*")/i', $img_tag, $img[$img_tag]);						
foreach($img[$img_tag][2] as $imges)
{
     $img_real= str_replace('"', '', $imges);
     check_image_file_for_webp_converter($img_real, $webp_on_page);
}`

тут конечно же в списке data-mobile-mobile-src|data-mobile-src-mini|data-mobile-src - это мои кастомные теги. как пример в том коде что я "от балды" нашел на Pikabu слудет использовать теги data-src|data-large-image


в старом коде надо было использовать не preg_match, а preg_match_all в месте где парсятся параметры у тега


так как я сторонник репощиториев, да и ваш код лучше, то оставляю себе вашу обновленную версию с изменениями от себя в строках 176-186.

Спасибо
