### ISSUE TITLE
Skips some files | Пропускает файлы

### ISSUE THREAD

**Issue by MASTER-SHAKE** [commeta/modxWebpConverter#2]
Здравствуйте, заметил что некоторые файлы не хотят конвертироваться и заново попадают в индекс, подскажите в чем может быть проблема

Пример файла который не хочет конвертироваться:
![zaken](https://user-images.githubusercontent.com/4558166/103315459-4d412c80-4a2e-11eb-97ec-79d7cee69570.jpg)

**Comment by commeta** [comment]
Здравствуйте, утилита cwebp спотыкается с ошибкой на этом файле:
Unsupported color conversion request
Error! Could not process file 103315459-4d412c80-4a2e-11eb-97ec-79d7cee69570.jpeg
Error! Cannot read input picture file '103315459-4d412c80-4a2e-11eb-97ec-79d7cee69570.jpeg'

**Comment by commeta** [comment]
Судя по всему проблема в цветовом профиле изображения, схожие проблемы есть у плагина WebP Express, который работает по той-же схеме. 
https://wordpress.org/support/topic/unsupported-color-conversion/
https://github.com/rosell-dk/webp-express/issues/329

**Comment by MASTER-SHAKE** [comment]
Да похоже проблема в преобразователе webp, кстати говоря - запустил сайт из под OpenServer, (т.к. под windows используется cwebp-110-windows-x64.exe) попробовал преобразовать на нем, всё получилось.
Спасибо за помощь!

**Comment by commeta** [comment]
Добавил патч, теперь если jpeg не может быть преобразован в webp через утилиту cwebp, тогда файл будет преобразован через GD. В этом варианте файл будет сконвертирован, обновите в плагине файл converter.php

**Comment by MASTER-SHAKE** [comment]
Отлично, большое спасибо!)
Кстати говоря добавил у себя в файле modx_plugin_webp_converter.php -  условие 
if(!function_exists('check_image_file_for_webp_converter')) { function check_image_file_for_webp_converter... }
if(!function_exists('rel2abs_img')) { function rel2abs_img... }

и перенес их выше в начало файла, дабы предотвратить ошибки (function already exist и тп.) которые возникают из-за кэширования в modx. Быть может это еще кому-то поможет :)

**Comment by commeta** [comment]
> modx_plugin_webp_converter.php - условие

Спасибо, закоммитил тоже.
