### ISSUE TITLE
To exclude the system directory from the parsing

### ISSUE THREAD

**Issue by D0br0sh4n** [commeta/modxWebpConverter#3]
Доброго дня.
Я думаю будет полезно исключить из парсинга системные директории modx. 
Не силён в PHP, задонатил бы за правки. 

[Скрин](https://psc.d0br0.ru/1611265303557.png)

**Comment by commeta** [comment]
Здравствуйте, тут все просто, в файле converter.php есть функция recursive_search_img в ней происходит обход дерева каталогов. Тут есть участок отвечающий за исключение подкаталогов.

```PHP
if( // Exclude subdirectories from search
	$file == '.' || $file == '..' || 
	strpos($full_path, BASE_PATH.DIRECTORY_SEPARATOR.'manager'.DIRECTORY_SEPARATOR) !== false ||
	strpos($full_path, BASE_PATH.DIRECTORY_SEPARATOR.'webp'.DIRECTORY_SEPARATOR) !== false
){
	continue;
}
```

В Вашем случае надо заменить этот участок, добавив условие:

```PHP
if( // Exclude subdirectories from search
	$file == '.' || $file == '..' || 
	strpos($full_path, BASE_PATH.DIRECTORY_SEPARATOR.'core'.DIRECTORY_SEPARATOR.'packages') !== false ||
	strpos($full_path, BASE_PATH.DIRECTORY_SEPARATOR.'manager'.DIRECTORY_SEPARATOR) !== false ||
	strpos($full_path, BASE_PATH.DIRECTORY_SEPARATOR.'webp'.DIRECTORY_SEPARATOR) !== false
){
	continue;
}
```

в таком случае подкаталог /core/packages будет проигнорирован!

**Comment by commeta** [comment]
Сделал еще проще, добавил в начале файла converter.php массив:
```PHP
$excludeSubdirectories= [
	DIRECTORY_SEPARATOR.'manager'.DIRECTORY_SEPARATOR,
	DIRECTORY_SEPARATOR.'webp'.DIRECTORY_SEPARATOR
];
```
теперь можно добавлять туда подкаталоги для исключения, через запятую, например:
```PHP
$excludeSubdirectories= [
	DIRECTORY_SEPARATOR.'core'.DIRECTORY_SEPARATOR.'packages',
	DIRECTORY_SEPARATOR.'manager'.DIRECTORY_SEPARATOR,
	DIRECTORY_SEPARATOR.'webp'.DIRECTORY_SEPARATOR
];
```

**Comment by D0br0sh4n** [comment]
Благодарю. А вообще какая идея была парсить все папки?

22 янв. 2021 г. 14:15:20 Евгений <notifications@github.com>:

**Comment by commeta** [comment]
> Благодарю.

Незачто, ставьте star!


> А вообще какая идея была парсить все папки?

Мы же не знаем где у кого что лежит, поэтому в базовых настройках исключаем из поиска подкаталог /manager и /webp
