### ISSUE TITLE
Вложенность url

### ISSUE THREAD

**Issue by GlobalOnce** [commeta/modxWebpConverter#8]
Здравствуйте! У меня такая проблема: если url имеет такой вид https://site.com или такой https://site.com/foo, то плагин подменяющий пути у изображений работает корректно, но если в url присутствует вложенность, например так https://site.com/foo/bar, то в таком случае подмены путей изображений не происходит.

**Comment by commeta** [comment]
> подмены путей изображений не происходит

Покажите живой пример, 

я сейчас проверил, все нормально

`<img src="/webp/wp-content/uploads/2016/01/logo-normal.png.webp"/> `
`<img src="https://dev.webdevops.ru/webp/wp-content/uploads/2016/01/logo-normal.png.webp"/> `
`<img src="/webp/wp-content/uploads/2016/01/logo-light.png.webp" /> `

**Comment by GlobalOnce** [comment]
https://maximove.ru/portfolio.html

**Comment by GlobalOnce** [comment]
Эта проблема также повторяется и на другом сайте

**Comment by shedko** [comment]
Не хватает знаний, чтобы понять почему у нас так, но может у Вас такая же конфигурация и перед строкой

`preg_match_all('/<img[^>]+>/i', $output, $result);`

добавили строчки
`
		$output = str_ireplace ("https://site.by", "" , $output);

		$output = str_ireplace ("src=\"img/", "src=\"/img/" , $output);
`

убрали полные пути, сделали чтобы не было img/img.png а было /img/img.png
( у нас все складывается в img а не assets)
решило проблемы
