### ISSUE TITLE
Исключить папки из сканирования и конвертирования

### ISSUE THREAD

**Issue by duron16** [commeta/modxWebpConverter#9]
Прям очень полезный и нужный инструмент, этот `modxWebpConverter`. Пока тестирую и все работает. 
Правда он сканирует всю файловую систему, а мне нужно часть закрыть от конвертирования.
Посмотрел код, и не увидел где бы можно перечислить список адресов что бы исключить. Есть такая возможность?

**Comment by commeta** [comment]
Да, в файле converter.php есть массив, строка 52.
Здесь вы можете добавить свой подкаталог относительно корня сайта, без слеша на конце.
В массиве уже присутствуют исключенные подкаталоги:

- /core/packages
- /tmp
- /manager
- /webp

`$excludeSubdirectories= [ // Exclude subdirectories from search
	DIRECTORY_SEPARATOR.'core'.DIRECTORY_SEPARATOR.'packages',
	DIRECTORY_SEPARATOR.'tmp',
	DIRECTORY_SEPARATOR.'manager',
	DIRECTORY_SEPARATOR.'webp'
];`
